### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by ajuser** [sameersemna/ci-flexigrid#3]
No exports with utf-8 encode

**Comment by sameersemna** [comment]
Issue unclear, please ellaborate.

**Comment by ajuser** [comment]
when you export to xls or csv, does not support UTF-8 characters, such as accents, ñ, etc.
Thanks

---

Antonio J.Páez Mauriño
Ingeniero Técnico Informático
algoparami@gmail.com
Tel: 955112935 - 607652246

Este mensaje de correo electrónico y sus documentos adjuntos están dirigidos  EXCLUSIVAMENTE a los destinatarios especificados. La información contenida puede ser CONFIDENCIAL y/o estar LEGALMENTE PROTEGIDA. Si usted recibe este mensaje por ERROR, por favor comuníqueselo inmediatamente al remitente y  ELIMÍNELO ya que usted  NO ESTA AUTORIZADO al uso, revelación, distribución, impresión o copia de toda o alguna parte de la información contenida. Gracias.

**Comment by sameersemna** [comment]
Please send me SQL dump of sample datatable with UTF-8 characters to test.

**Comment by ajuser** [comment]
Ok, thanks.

2015-04-09 11:05 GMT+02:00 Sameer Shemna notifications@github.com:

> Please send me SQL dump of sample datatable with UTF-8 characters to test.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sameersemna/ci-flexigrid/issues/3#issuecomment-91162828
> .

## 

---

Antonio J.Páez Mauriño
Ingeniero Técnico Informático
algoparami@gmail.com
Tel: 955112935 - 607652246

Este mensaje de correo electrónico y sus documentos adjuntos están
dirigidos  EXCLUSIVAMENTE a los destinatarios especificados. La información
contenida puede ser CONFIDENCIAL y/o estar LEGALMENTE PROTEGIDA. Si usted
recibe este mensaje por ERROR, por favor comuníqueselo inmediatamente al
remitente y  ELIMÍNELO ya que usted  NO ESTA AUTORIZADO al uso, revelación,
distribución, impresión o copia de toda o alguna parte de la información
contenida. Gracias.

This e-mail message and any attached files are intended SOLELY for the
addressee/s identified herein. It may contain CONFIDENTIAL and/or LEGALLY
PRIVILEGED  information. If you receive this message in ERROR, please
immediately notify the sender and DELETE it since you ARE NOT AUTHORIZED
to use, disclose, distribute, print or copy all or part of the contained
information. Thank you

**Comment by sameersemna** [comment]
???no attached .sql file found
regards 
| Sameer Shemna 
Developer / Designer 
 |
| website | vCard | email |
|     |
| Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender. |

```
 On Thursday, April 9, 2015 11:41 AM, ajuser <notifications@github.com> wrote:
```

 Ok, thanks.

2015-04-09 11:05 GMT+02:00 Sameer Shemna notifications@github.com:

> Please send me SQL dump of sample datatable with UTF-8 characters to test.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sameersemna/ci-flexigrid/issues/3#issuecomment-91162828
> .

## 

---

Antonio J.Páez Mauriño
Ingeniero Técnico Informático
algoparami@gmail.com
Tel: 955112935 - 607652246

Este mensaje de correo electrónico y sus documentos adjuntos están
dirigidos EXCLUSIVAMENTE a los destinatarios especificados. La información
contenida puede ser CONFIDENCIAL y/o estar LEGALMENTE PROTEGIDA. Si usted
recibe este mensaje por ERROR, por favor comuníqueselo inmediatamente al
remitente y ELIMÍNELO ya que usted NO ESTA AUTORIZADO al uso, revelación,
distribución, impresión o copia de toda o alguna parte de la información
contenida. Gracias.

This e-mail message and any attached files are intended SOLELY for the
addressee/s identified herein. It may contain CONFIDENTIAL and/or LEGALLY
PRIVILEGED information. If you receive this message in ERROR, please
immediately notify the sender and DELETE it since you ARE NOT AUTHORIZED
to use, disclose, distribute, print or copy all or part of the contained
information. Thank you

**Comment by ajuser** [comment]
CREATE TABLE IF NOT EXISTS `countries` (
  `id` int(11) NOT NULL auto_increment,
  `iso` char(2) NOT NULL,
  `name` varchar(80) NOT NULL,
  `printable_name` varchar(80) NOT NULL,
  `iso3` char(3) default NULL,
  `numcode` smallint(6) default NULL,
  `created_date` date default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=240 ;

## 

## -- Volcado de datos para la tabla `countries`

INSERT INTO `countries` (`id`, `iso`, `name`, `printable_name`, `iso3`, `numcode`, `created_date`) VALUES
(211, 'TH', 'España', 'España', 'THA', 764, '2012-03-27'),
(212, 'TL', 'Afganistán', 'Afganistán', NULL, NULL, '2011-09-29'),
(213, 'TG', 'Etiopía', 'Etiopía', 'TGO', 768, '2011-09-09');

**Comment by sameersemna** [comment]
Fixed by last commit
